package LexicalAnalysis;

public enum TokenType {
	//保留字
	AUTO,BREAK,CASE,
	CHAR,CONSTCONTINUE,
	DEFAULT,DO,DOUBLE,
	ELSE,ENUM,EXTERN,
	FLOAT,FOR,GOTO,
	IF,INT,LONG,
	REDISTER,RETURN,SHORT,
	SIGNED,SIZEOF,STATIC,
	STRUCT,SWITCH,TYPEDEF,
	UNION,UNSIGNED,VOID,
	VOLATILE,WHILE,
	//标识符
	ID, NUM,
	//界限符
	ASSIGN, EQ, LT, PLUS, MINUS, TIMES, OVER, LPAREN, RPAREN, SEMI, COMMA, DEFINE, ERROR,ENDFILE,BLPAREN,BRPAREN,INC,DEC,LTEQ,RTEQ,AND,OR,NOTEQ

}
